name: cmss_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webviewx_plus: ^0.5.0
  # Adicionando mais dependências úteis
  url_launcher: ^6.1.7 # para abrir a página web com o endereço de IP digitado

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "C:/Users/User/Pictures/icon.png" # Caminho para o ícone padrão
  adaptive_icon_background: "#FFFFFF"    # Cor de fundo para o Android
  adaptive_icon_foreground: "C:/Users/User/Pictures/screen_splash.png" # Imagem para o ícone adaptativo

flutter:
  uses-material-design: true

  # Para adicionar os ícones personalizados
  assets:
    - C:/Users/User/Pictures/icon.png
    - C:/Users/User/Pictures/screen_splash.png
  # Para adicionar fontes personalizadas, se necessário:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
